#!/bin/sh
# Teste l'analyse lexicale

# Pour tous les fichiers tests de syntaxe
RED="$(tput bold ; tput setaf 1)"
GREEN="$(tput bold ; tput setaf 2)"
NC="$(tput sgr0)" # No Color

cd ../../../ 
for fich in $* 
do
	
	echo "--------------- $fich ---------------"
	java ProjetCompil.Verif.Src.TestVerif ProjetCompil/Verif/Test/$fich 
	if [ $? -ne 0 ]
	then
		echo "${RED}veriftest $fich FAILED${NC}"
	else
		echo "${GREEN}veriftest $fich OK${NC}"
	fi
	echo ""
	
done
cd ProjetCompil/Syntaxe/Test
