#!/bin/sh
# Teste l'analyse lexicale

# Pour tous les fichiers tests de syntaxe
RED="$(tput bold ; tput setaf 1)"
GREEN="$(tput bold ; tput setaf 2)"
NC="$(tput sgr0)" # No Color

fich1=`ls ../Test/success/*.cas`
fich2=`ls ../Test/fail/*.cas`

for fich in $fich1  
do
	
	echo "--------------- $fich (doit reussir) ---------------"
	java ProjetCompil.Verif.Src.TestVerif $fich > /dev/null
	if [ $? -ne 0 ]
	then
		echo "${RED}veriftest $fich FAILED${NC}"
	else
		echo "${GREEN}veriftest $fich OK${NC}"
	fi
	echo ""
	
done

for fich in $fich2
do
	
	echo "--------------- $fich (doit echouer) ---------------"
	java ProjetCompil.Verif.Src.TestVerif $fich 
	if [ $? -ne 0 ]
	then
		echo "${GREEN}veriftest $fich OK${NC}"
	else
		echo "${RED}veriftest $fich FAILED${NC}"
	fi
	echo ""
	
done
