#!/bin/bash
# Teste l'analyse lexicale

# Pour tous les fichiers tests de syntaxe
RED="$(tput bold ; tput setaf 1)"
GREEN="$(tput bold ; tput setaf 2)"
NC="$(tput sgr0)" # No Color

for fich in $* 
do
	
	cd ../../../ 
	java ProjetCompil.Syntaxe.Src.TestLex ProjetCompil/Syntaxe/Test/$fich 
	if [ $? -ne 0 ]
	then
		echo -e "${RED}lextest $fich FAILED${NC}"
	else
		echo -e "${GREEN}lextest $fich OK${NC}"
	fi
	
	cd ProjetCompil/Syntaxe/Test
done

