#!/bin/sh
# Teste l'analyse lexicale

# Pour tous les fichiers tests de syntaxe
RED="$(tput bold ; tput setaf 1)"
GREEN="$(tput bold ; tput setaf 2)"
NC="$(tput sgr0)" # No Color

for fich in $* 
do
	
	cd ../../../ 
	java ProjetCompil.Syntaxe.Src.TestSynt ProjetCompil/Syntaxe/Test/$fich 
	if [ $? -ne 0 ]
	then
		echo "${RED}syntest $fich FAILED${NC}"
	else
		echo "${GREEN}syntest $fich OK${NC}"
	fi
	
	cd ProjetCompil/Syntaxe/Test
done
